# $FreeBSD$

PORTNAME=	git-extras
PORTVERSION=	4.4.0
CATEGORIES=	devel

MAINTAINER=	igor.ostapenko@gmail.com
COMMENT=	Sub-commands for repo summary, repl, changelog population, and more

LICENSE=	MIT

RUN_DEPENDS=	git:devel/git \
		bash:shells/bash

USES=		gmake

USE_GITHUB=	yes
GH_ACCOUNT=	tj

NO_BUILD=	yes

.include <bsd.port.mk>
